runtime: nodejs22
handlers:

  - url: /(.*\.(json|ico|js|css|svg|png|jpg|jpeg|txt|map|webmanifest))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js|css|svg|png|jpg|jpeg|txt|map|webmanifest)$
    secure: always

  - url: .*
    static_files: build/index.html
    upload: build/index.html
    secure: always